#!/bin/bash

echo "[`date`] Cleanup starting." >> /var/log/cron.log
(cd /opt/cnaas/venv/cnaas-nac/src; source ../../bin/activate; python3 -m cnaas_nac.tools.db_cleanup) >> /var/log/cron.log
echo "[`date`] Cleanup finished." >> /var/log/cron.log
