#!/bin/bash

echo "[`date`] Replication starting."  >> /var/log/cron.log
(cd /opt/cnaas/venv/cnaas-nac/src/;source ../../bin/activate;python3 -m cnaas_nac.tools.db_replicator -e)
echo "[`date`] Replication finished." >> /var/log/cron.log