#
# Jenkins pipeline for CNaaS
#

disabled: false

git:
  branch: develop
  extensions:
    shallow_clone: true

extra_jobs:
  # Jobs for the develop branch
  - name: nac-authapi
    git:
      branch: develop
    builders:
      - docker
    docker_name: cnaas/nac-authapi
    docker_context_dir: docker/api

  - name: nac-radius
    git:
      branch: develop
    builders:
      - docker
    docker_name: cnaas/nac-radius
    docker_context_dir: docker/radius

  - name: nac-postgres
    git:
      branch: develop
    builders:
      - docker
    docker_name: cnaas/nac-postgres
    docker_context_dir: docker/postgres

  # Jobs for the master branch
  - name: nac-authapi-master
    git:
      branch: master
    builders:
      - docker
    docker_tags:
      - "master"
    docker_name: cnaas/nac-authapi
    docker_context_dir: docker/api

  - name: nac-radius-master
    git:
      branch: master
    builders:
      - docker
    docker_tags:
      - "master"
    docker_name: cnaas/nac-radius
    docker_context_dir: docker/radius

  - name: nac-postgres-master
    git:
      branch: master
    builders:
      - docker
    docker_tags:
      - "master"
    docker_name: cnaas/nac-postgres
    docker_context_dir: docker/postgres
