#
# Jenkins pipeline for CNaaS
#

disabled: false
# downstream:
#   - cnaas-radius
#   - cnaas-authapi

git:
  branch: develop
  extensions:
    shallow_clone: true

script:
  - "python3.7 -m venv venv"
  - ". venv/bin/activate"
  - "pip install --upgrade setuptools pip wheel mypy"
  - "pip install --index-url https://pypi.sunet.se -r requirements.txt"
  - "nosetests --with-xunit"

extra_jobs:
  # Jobs for the develop branch
  - name: nac-authapi
    git:
      brach: develop
    builders:
      - docker
    docker_name: cnaas/nac-authapi
    docker_context_dir: docker/api

  - name: nac-radius
    git:
      brach: develop
    builders:
      - docker
    docker_name: cnaas/nac-radius
    docker_context_dir: docker/radius

  - name: nac-postgres
    git:
      brach: develop
    builders:
      - docker
    docker_name: cnaas/nac-postgres
    docker_context_dir: docker/postgres

  # Jobs for the master branch
  - name: nac-authapi
    git:
      branch: master
    builders:
      - docker
    docker_tags:
      - "v0.1.0"
    docker_name: cnaas/nac-authapi
    docker_context_dir: docker/api

  - name: nac-radius
    git:
      branch: master
    builders:
      - docker
    docker_tags:
      - "v0.1.0"
    docker_name: cnaas/radius
    docker_context_dir: docker/nac-radius

  - name: nac-postgres
    git:
      branch: master
    builders:
      - docker
    docker_tags:
      - "v0.1.0"
    docker_name: cnaas/nac-postgres
    docker_context_dir: docker/postgres
