"""Table for OUI

Revision ID: 1e4142701fbb
Revises: e76a7f120db0
Create Date: 2019-11-25 14:36:33.114792

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '1e4142701fbb'
down_revision = 'e76a7f120db0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_oui',
                    sa.Column('id', sa.INTEGER(), autoincrement=True,
                              nullable=False),
                    sa.Column('oui', sa.TEXT(), autoincrement=False,
                              nullable=False),
                    sa.Column('description', sa.TEXT(), autoincrement=False,
                              nullable=True),
                    sa.PrimaryKeyConstraint('id', name='device_oui_pkey'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('device_oui')
    # ### end Alembic commands ###
