"""New table, radgroups.

Revision ID: 4843367789e9
Revises: c92d5baa30aa
Create Date: 2022-08-30 13:40:15.366669

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.schema import CreateSequence, Sequence

# revision identifiers, used by Alembic.
revision = '4843367789e9'
down_revision = 'c92d5baa30aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(CreateSequence(Sequence('radgroups_id_seq')))
    op.create_table('radgroups',
                    sa.Column('id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('groupname', sa.TEXT(),
                              autoincrement=False, nullable=False),
                    sa.Column('fieldname', sa.TEXT(),
                              autoincrement=False, nullable=False),
                    sa.Column('condition', sa.TEXT(),
                              autoincrement=False, nullable=False))
    op.alter_column('radgroups', 'id', nullable=False,
                    server_default=sa.text("nextval('radgroups_id_seq'::regclass)"))
    op.create_index('radgroups_groupname', 'radgroups',
                    ['groupname'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('radgroups')
    op.execute("drop sequence radgroups_id_seq")
    # ### end Alembic commands ###
