"""Added freeradius tables

Revision ID: 538170dfe877
Revises: a3f3bc390462
Create Date: 2019-05-24 09:09:24.752289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '538170dfe877'
down_revision = ''
branch_labels = None
depends_on = None


def upgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('radreply',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.Unicode(length=64), nullable=False),
    sa.Column('attribute', sa.Unicode(length=64), nullable=True),
    sa.Column('op', sa.Unicode(length=2), nullable=True),
    sa.Column('value', sa.Unicode(length=253), nullable=True),                    
    sa.PrimaryKeyConstraint('id'),
    )
    op.create_table('radcheck',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.Unicode(length=64), nullable=False),
    sa.Column('attribute', sa.Unicode(length=64), nullable=True),
    sa.Column('op', sa.Unicode(length=2), nullable=True),
    sa.Column('value', sa.Unicode(length=253), nullable=True),                    
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('radreply')
    op.drop_table('radcheck')
    # ### end Alembic commands ###
