"""New columns for access_start and access_stop.

Revision ID: c92d5baa30aa
Revises: 425659aef19c
Create Date: 2022-08-25 10:45:48.861484

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c92d5baa30aa'
down_revision = '425659aef19c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("raduserinfo", sa.Column('access_start', postgresql.TIMESTAMP(
        timezone=True), autoincrement=False, nullable=True))
    op.add_column("raduserinfo", sa.Column('access_stop', postgresql.TIMESTAMP(
        timezone=True), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("raduserinfo", "access_start")
    op.drop_column("raduserinfo", "access_stop")
    # ### end Alembic commands ###
