version: '3'
services:
  nac_api:
    build: ./api/
    ports:
      - 5001:5001
  nac_radius:
    build: ./radius
    ports:
      - 1812:1812/udp
      - 1813:1813/udp
  nac_postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=cnaas
      - POSTGRES_PASSWD=cnaas
      - POSTGRES_DB=nac
    
