version: '3'
services:
  nac_api:
    build: ./api/
    ports:
      - 5001:5001
    networks:
      - cnaas
  nac_radius:
    build: ./radius
    ports:
      - 1812:1812/udp
      - 1813:1813/udp
    networks:
      - cnaas
networks:
  cnaas:
